pipeline {
    agent any
    stages {
        stage('Build') { 
            steps {
                sh 'cd devops_api && dotnet restore'
                sh 'cd devops_api && dotnet build'
            }
        }
        // stage("Commit changes back to production repo"){
        //     steps{
        //         sh 'git checkout --track origin/dev'
        //         sh 'git checkout --track origin/master'
        //         sh 'git merge dev'
        //         withCredentials([usernamePassword(credentialsId: '3abcc784-22bb-4e05-b6a8-b230ae6fbbf9', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
        //             sh('git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/vineetb95/TryAtJenkins' )
        //         }
        //     }
        // }
    }
    post {
    // Clean after build
        always {
            cleanWs()
        }
    }
}
