pipeline {
    agent any
    tools {nodejs "nodeLatest"}
    stages {
        stage('Deploy to development') { 
            steps {
                sh 'echo "Add build steps here"'
                sh 'cd web-client && npm install'
                sh 'cd web-client && npm run build'
                withAWS(region:'ap-south-1', credentials:'IAMuserLTI') {
                    s3Upload(bucket: 'reactdeploydemo', file:'web-client/build/')
                }
                emailext attachLog: true, body: 'Proceed or abort the deployment process at $RUN_DISPLAY_URL.', to: 'vineet.bakshi95@gmail.com', recipientProviders: [developers()], subject: '$PROJECT_NAME - Build # $BUILD_NUMBER - Permission required for deploying to production.'
            }
        }
        stage('Deploy to production') {
            input{
              message 'Do you want to proceed ??'
            }
            steps {
                withAWS(region:'ap-south-1', credentials:'IAMuserLTI') {
                    s3Copy fromBucket: 'reactdeploydemo', toBucket: 'forstaticwebhosting'
                }
            }
        }
        stage("Commit changes back to production repo"){
            steps{
                sh 'git checkout --track origin/dev'
                sh 'git checkout --track origin/master'
                sh 'git merge dev'
                withCredentials([usernamePassword(credentialsId: 'mygithubcredentials', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                    sh('git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/vineetb95/WebAppLTI' )
                }
            }
        }
    }
    post {
    // Clean after build
        always {
            cleanWs()
        }
    }
}
